// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:e3576da5-f746-4866-8d40-6d08343a2e8c",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_n3PQ82tXW",
    "aws_user_pools_web_client_id": "3n5bd6e6o1ukh5tuqehm8d1sjq",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://qn6lutf7gjfphaqko2oaluhmri.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
